[debug] [2018-02-12T03:53:41.991Z] ----------------------------------------------------------------------
[debug] [2018-02-12T03:53:41.994Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve
[debug] [2018-02-12T03:53:41.994Z] CLI Version:   3.17.4
[debug] [2018-02-12T03:53:41.995Z] Platform:      darwin
[debug] [2018-02-12T03:53:41.995Z] Node Version:  v8.6.0
[debug] [2018-02-12T03:53:41.995Z] Time:          Sun Feb 11 2018 19:53:41 GMT-0800 (PST)
[debug] [2018-02-12T03:53:41.995Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-02-12T03:53:42.007Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-02-12T03:53:42.007Z] > authorizing via signed-in user
[debug] [2018-02-12T03:53:42.009Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2018-02-12T03:53:42.010Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 { refresh_token: '1/C_LSk6IdII3TEsq_7RN67wEhlWaaractbiguuqiCL_I',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  grant_type: 'refresh_token',
  scope: 'email https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloudplatformprojects.readonly https://www.googleapis.com/auth/firebase openid' } 
 Sun Feb 11 2018 19:53:42 GMT-0800 (PST)
[debug] [2018-02-12T03:53:42.170Z] <<< HTTP RESPONSE 200
[debug] [2018-02-12T03:53:42.181Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/printer-1c171  
  
 Sun Feb 11 2018 19:53:42 GMT-0800 (PST)
[debug] [2018-02-12T03:53:42.499Z] <<< HTTP RESPONSE 200
[debug] [2018-02-12T03:53:42.499Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/printer-1c171/tokens  
  
 Sun Feb 11 2018 19:53:42 GMT-0800 (PST)
[debug] [2018-02-12T03:53:42.937Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/kevincrum/Desktop/116/3d-print/src'...
[info] 
[debug] [2018-02-12T03:53:42.940Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/printer-1c171  
  
 Sun Feb 11 2018 19:53:42 GMT-0800 (PST)
[debug] [2018-02-12T03:53:43.447Z] <<< HTTP RESPONSE 200
[debug] [2018-02-12T03:53:43.448Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/198617925096/clients/_:getWebAppConfig  
  
 Sun Feb 11 2018 19:53:43 GMT-0800 (PST)
[debug] [2018-02-12T03:53:44.023Z] <<< HTTP RESPONSE 200
[debug] [2018-02-12T03:53:44.062Z] TypeError: Cannot read property 'public' of undefined
    at Server.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/serve/hosting.js:34:17)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Server.emit (events.js:207:7)
    at emitListeningNT (net.js:1371:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2018-02-12T03:56:20.807Z] ----------------------------------------------------------------------
[debug] [2018-02-12T03:56:20.810Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve
[debug] [2018-02-12T03:56:20.810Z] CLI Version:   3.17.4
[debug] [2018-02-12T03:56:20.810Z] Platform:      darwin
[debug] [2018-02-12T03:56:20.810Z] Node Version:  v8.6.0
[debug] [2018-02-12T03:56:20.810Z] Time:          Sun Feb 11 2018 19:56:20 GMT-0800 (PST)
[debug] [2018-02-12T03:56:20.810Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-02-12T03:56:20.824Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-02-12T03:56:20.825Z] > authorizing via signed-in user
[debug] [2018-02-12T03:56:20.827Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/printer-1c171  
  
 Sun Feb 11 2018 19:56:20 GMT-0800 (PST)
[debug] [2018-02-12T03:56:21.310Z] <<< HTTP RESPONSE 200
[debug] [2018-02-12T03:56:21.311Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/printer-1c171/tokens  
  
 Sun Feb 11 2018 19:56:21 GMT-0800 (PST)
[debug] [2018-02-12T03:56:21.925Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/kevincrum/Desktop/116/3d-print/src'...
[info] 
[debug] [2018-02-12T03:56:21.929Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/printer-1c171  
  
 Sun Feb 11 2018 19:56:21 GMT-0800 (PST)
[debug] [2018-02-12T03:56:22.470Z] <<< HTTP RESPONSE 200
[debug] [2018-02-12T03:56:22.470Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/198617925096/clients/_:getWebAppConfig  
  
 Sun Feb 11 2018 19:56:22 GMT-0800 (PST)
[debug] [2018-02-12T03:56:23.204Z] <<< HTTP RESPONSE 200
[debug] [2018-02-12T03:56:23.235Z] TypeError: Cannot read property 'public' of undefined
    at Server.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/serve/hosting.js:34:17)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Server.emit (events.js:207:7)
    at emitListeningNT (net.js:1371:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[error] 
[error] Error: An unexpected error has occurred.
